// LOGIC OPERATOR
// jika didalam if (....) ada 2 kondisi yang di pertimbangkan / check di dalam ()
// CASE : misalkan siswa boleh masuk ke dalam kampus jika membawa tas dan sepatu
let bawaTas = true
let bawaSepatu = true
if (bawaTas && bawaSepatu) {
    // boleh masuk
} else {
    // tidak boleh masuk
}

//  OPERATOR : AND (&&), OR(||), NEGASI / KEBALIKAN (!)
//  Hasil perbandingan menggunakan logic
let pesan = "Hello World"
console.log(pesan) // ctrl + shift + bawah => untuk copas kebawah dengan cepat
console.log(pesan)
console.log(pesan)
console.log(pesan)
console.log(pesan)
console.log(pesan)